version: '3.8'

services:
  fastapi-dev:
    build: .
    container_name: fastapi-dev
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
